#!/usr/bin/env python3
"""
Review Report Generator
code_review_analyzer.py의 JSON 결과를 마크다운 리뷰 리포트로 변환
"""

import json
from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime


class ReviewReportGenerator:
    """리뷰 리포트 생성기"""

    def __init__(self, input_path: str = ".claude/review-report.json"):
        self.input_path = Path(input_path)
        self.data: Dict[str, Any] = {}

    def load(self) -> bool:
        """JSON 리포트 로드"""
        if not self.input_path.exists():
            print(f"⚠️  Input file not found: {self.input_path}")
            return False

        try:
            with open(self.input_path, 'r', encoding='utf-8') as f:
                self.data = json.load(f)
            print(f"✅ Loaded: {self.input_path}")
            return True
        except json.JSONDecodeError as e:
            print(f"⚠️  Invalid JSON: {e}")
            return False

    def generate(self) -> str:
        """마크다운 리포트 생성"""
        if not self.data:
            return "# Code Review Report\n\nNo data available."

        lines = []

        # 헤더
        lines.append("# Code Review Report")
        lines.append("")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")

        # 요약
        summary = self.data.get("summary", {})
        lines.append("## Summary")
        lines.append("")
        lines.append("| Metric | Count |")
        lines.append("|--------|-------|")
        lines.append(f"| 🔴 Errors | {summary.get('error', 0)} |")
        lines.append(f"| 🟡 Warnings | {summary.get('warning', 0)} |")
        lines.append(f"| 🔵 Info | {summary.get('info', 0)} |")
        lines.append(f"| **Total** | **{summary.get('total', 0)}** |")
        lines.append(f"| 🔧 Auto-fixable | {summary.get('auto_fixable', 0)} |")
        lines.append(f"| 📁 Files with issues | {summary.get('files_with_issues', 0)} |")
        lines.append("")

        # 이슈 목록
        issues = self.data.get("issues", [])

        if issues:
            # Critical Issues (Errors)
            errors = [i for i in issues if i.get("severity") == "error"]
            if errors:
                lines.append("## 🔴 Critical Issues (Must Fix)")
                lines.append("")
                lines.extend(self._format_issues(errors))
                lines.append("")

            # Warnings
            warnings = [i for i in issues if i.get("severity") == "warning"]
            if warnings:
                lines.append("## 🟡 Warnings (Should Fix)")
                lines.append("")
                lines.extend(self._format_issues(warnings[:20]))  # 상위 20개만
                if len(warnings) > 20:
                    lines.append(f"*... and {len(warnings) - 20} more warnings*")
                lines.append("")

            # Info
            infos = [i for i in issues if i.get("severity") == "info"]
            if infos:
                lines.append("## 🔵 Suggestions (Nice to Have)")
                lines.append("")
                lines.extend(self._format_issues(infos[:10]))  # 상위 10개만
                if len(infos) > 10:
                    lines.append(f"*... and {len(infos) - 10} more suggestions*")
                lines.append("")

        # Top Files with Issues
        top_files = summary.get("top_files", [])
        if top_files:
            lines.append("## 📁 Top Files with Issues")
            lines.append("")
            lines.append("| File | Issues |")
            lines.append("|------|--------|")
            for file_path, count in top_files[:10]:
                # 경로가 너무 길면 축약
                display_path = file_path if len(file_path) < 60 else "..." + file_path[-57:]
                lines.append(f"| `{display_path}` | {count} |")
            lines.append("")

        # Recommendations
        recommendations = self.data.get("recommendations", [])
        if recommendations:
            lines.append("## 💡 Recommendations")
            lines.append("")
            for rec in recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by `script/review_report_generator.py`*")

        return "\n".join(lines)

    def _format_issues(self, issues: List[Dict]) -> List[str]:
        """이슈 목록 포맷팅"""
        lines = []

        # 파일별로 그룹핑
        by_file: Dict[str, List[Dict]] = {}
        for issue in issues:
            file = issue.get("file", "unknown")
            if file not in by_file:
                by_file[file] = []
            by_file[file].append(issue)

        for file, file_issues in by_file.items():
            # 파일명 (경로 축약)
            display_file = file if len(file) < 50 else "..." + file[-47:]
            lines.append(f"### `{display_file}`")
            lines.append("")

            for issue in file_issues[:5]:  # 파일당 최대 5개
                line = issue.get("line", 0)
                col = issue.get("column", 0)
                message = issue.get("message", "")
                rule = issue.get("rule", "")
                tool = issue.get("tool", "")
                fixable = "🔧" if issue.get("fixable") else ""

                location = f":{line}" if line else ""
                if col:
                    location += f":{col}"

                rule_info = f"[{rule}]" if rule else ""
                tool_info = f"({tool})" if tool else ""

                lines.append(f"- **Line {line}** {rule_info} {tool_info} {fixable}")
                lines.append(f"  - {message}")

            if len(file_issues) > 5:
                lines.append(f"  - *... and {len(file_issues) - 5} more issues in this file*")

            lines.append("")

        return lines

    def save(self, output_path: str) -> None:
        """마크다운 파일 저장"""
        report = self.generate()

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        with open(path, 'w', encoding='utf-8') as f:
            f.write(report)

        print(f"📄 Report saved to: {path}")


def main():
    """CLI 실행"""
    import argparse

    parser = argparse.ArgumentParser(description="Review Report Generator")
    parser.add_argument(
        "--input", "-i",
        default=".claude/review-report.json",
        help="Input JSON file from code_review_analyzer.py"
    )
    parser.add_argument(
        "--output", "-o",
        default=".claude/review-report.md",
        help="Output markdown file"
    )
    parser.add_argument(
        "--print",
        action="store_true",
        help="Print report to stdout instead of saving"
    )

    args = parser.parse_args()

    generator = ReviewReportGenerator(input_path=args.input)

    if not generator.load():
        print("\n💡 Tip: Run code_review_analyzer.py first:")
        print("   python script/code_review_analyzer.py --output .claude/review-report.json")
        return

    if args.print:
        print("\n" + generator.generate())
    else:
        generator.save(args.output)

        # 요약 출력
        summary = generator.data.get("summary", {})
        print(f"\n📊 Summary:")
        print(f"  - Errors: {summary.get('error', 0)}")
        print(f"  - Warnings: {summary.get('warning', 0)}")
        print(f"  - Info: {summary.get('info', 0)}")
        print(f"  - Auto-fixable: {summary.get('auto_fixable', 0)}")


if __name__ == "__main__":
    main()
